services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - '8000:8000'
    command: >
      sh -c "
            /py/bin/python manage.py wait_for_db &&
            /py/bin/python manage.py makemigrations &&
            /py/bin/python manage.py migrate &&
            /py/bin/python manage.py create_periodic_task &&
            /py/bin/python manage.py collectstatic --noinput &&
            /py/bin/python manage.py runserver 0.0.0.0:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    command: >
      sh -c "
            /py/bin/python manage.py wait_for_db &&
            watchmedo auto-restart --directory=./ --pattern='*.py' --recursive -- celery -A app worker --loglevel=info --pool=solo"

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    command: >
      sh -c "
            /py/bin/python manage.py wait_for_db &&
            watchmedo auto-restart --directory=./ --pattern='*.py' --recursive -- celery -A app beat --loglevel=info"
