# Generated by Django 5.0.12 on 2025-02-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_dip_like_reply_thread_view_vote_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voting_power',
            field=models.DecimalField(decimal_places=0, max_digits=32),
        ),
    ]
