# Generated by Django 5.0.12 on 2025-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_dip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dip',
            name='proposal_type',
            field=models.CharField(choices=[('0', 'Transfer'), ('1', 'Upgrade')], default='0', max_length=20),
        ),
    ]
