# Generated by Django 5.0.12 on 2025-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_dip_proposal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dip',
            name='proposal_type',
            field=models.CharField(choices=[('0', 'Transfer'), ('1', 'Upgrade'), ('2', 'Module Upgrade'), ('3', 'Presale'), ('4', 'Presale Pause'), ('5', 'Presale Withdraw'), ('6', 'Pause'), ('7', 'Unpause')], default='0', max_length=20),
        ),
    ]
