# Generated by Django 5.0.12 on 2025-02-15 10:30

import core.validators.eth_network_validator
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('dao_image', models.ImageField(upload_to='images/dao', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('cover_image', models.ImageField(null=True, upload_to='images/dao', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('slug', models.CharField(max_length=10, null=True, unique=True)),
                ('socials', models.JSONField(blank=True, help_text='store socials and whitepaper as a json object', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dip_count', models.PositiveIntegerField(default=0)),
                ('dao_name', models.CharField(max_length=255, null=True)),
                ('token_name', models.CharField(max_length=50)),
                ('network', models.IntegerField(validators=[core.validators.eth_network_validator.validate_network])),
                ('symbol', models.CharField(max_length=5)),
                ('total_supply', models.DecimalField(decimal_places=0, max_digits=32, null=True)),
                ('version', models.CharField(default='1.0.0')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_address', models.CharField(max_length=42)),
                ('token_address', models.CharField(max_length=42)),
                ('treasury_address', models.CharField(max_length=42)),
                ('staking_address', models.CharField(max_length=42)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_contracts', to='dao.dao')),
            ],
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=32)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dao_stakers', to='dao.dao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='stake',
            index=models.Index(fields=['dao'], name='dao_stake_dao_id_7ca6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='stake',
            index=models.Index(fields=['user'], name='dao_stake_user_id_7d5c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='stake',
            index=models.Index(fields=['-amount'], name='dao_stake_amount_262f87_idx'),
        ),
    ]
