# Generated by Django 5.0.12 on 2025-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_dao_contract_stake_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stake',
            name='voting_power',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=32),
        ),
    ]
