# Generated by Django 5.0.12 on 2025-03-01 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0003_stake_voting_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presale_contract', models.CharField(max_length=42)),
                ('total_token_amount', models.DecimalField(decimal_places=0, max_digits=32)),
                ('initial_price', models.DecimalField(decimal_places=0, max_digits=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('current_tier', models.PositiveIntegerField(default=0)),
                ('current_price', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('remaining_in_tier', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('total_remaining', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('total_raised', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presales', to='dao.dao')),
            ],
            options={
                'indexes': [models.Index(fields=['dao'], name='dao_presale_dao_id_bfca4c_idx'), models.Index(fields=['status'], name='dao_presale_status_699e22_idx')],
            },
        ),
    ]
