# Generated by Django 5.0.12 on 2025-03-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0005_presaletransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='deployment_block',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
