# Generated by Django 5.0.12 on 2025-03-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0006_presale_deployment_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presaletransaction',
            name='eth_amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='presaletransaction',
            name='token_amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
