# Generated by Django 5.0.13 on 2025-03-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0007_alter_presaletransaction_eth_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_balance', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('native_balance', models.DecimalField(decimal_places=0, default=0, max_digits=32)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasury_balance', to='dao.dao')),
            ],
            options={
                'indexes': [models.Index(fields=['dao'], name='dao_treasur_dao_id_58b977_idx')],
            },
        ),
    ]
