# Generated by Django 5.0.13 on 2025-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0008_treasury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasury',
            name='native_balance',
        ),
        migrations.RemoveField(
            model_name='treasury',
            name='token_balance',
        ),
        migrations.AddField(
            model_name='treasury',
            name='balances',
            field=models.JSONField(default=dict, help_text='Token balances with addresses as keys'),
        ),
    ]
